samantha/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog import views

urlpatterns = [
	url('login/',auth_views.LoginView.as_view(template_name = 'blog/login.html'), name = 'login'),
	url('logout/',auth_views.LogoutView.as_view(template_name = 'blog/logout.html'), name = 'logout'),
    url(r'^admin/', admin.site.urls),
    url('home/',views.home , name = 'home'),
    url('register/',views.register , name = 'register'),
    url('post/',views.PostCreateView, name = 'post_'),
    url('',views.indexView)
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
from django.urls import reverse




class Post(models.Model):
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	title = models.CharField(max_length=100, blank = True)
	date = models.DateTimeField(default = timezone.now)
	content = models.TextField()

	image = models.ImageField(default='default.jpeg', upload_to='mobile_uploads')


	def get_absolute_url(self):
		return reverse('home')

	def save(self, *args, **kwargs):
		super(Post, self).save(*args, **kwargs)
		img = Image.open(self.image.path)
		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)

	def __str__(self):
		return self.author

blog/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
import datetime
from .models import Post

class UserRegistration(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

	class meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2' )



class PostForm(forms.ModelForm):
    
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Post
        fields = ("__all__")

blog/views.py
from django.shortcuts import render, redirect
from urllib import request
from django.http import HttpResponse
from django.template import Context
from django.contrib.auth.models import User
from .forms import UserRegistration,PostForm  #so we can add password to registration field 
from django.contrib import messages
from .models import Post
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.core import serializers


# generic = [{'author':'Reshoketswe','content':'Sample Content', 'date':'20-20-2020' , 'title':'sample tile'}]

generic = Post.objects.all()


def home(request):
	context = {'key_1':generic}
	return render(request, 'blog/home.html',context = context)


def register(request):
	if request.method == 'POST':
		f = UserRegistration(request.POST)
		if f.is_valid():
			f.save()
			messages.success(request,'You have been registered succesfully')
			return redirect('register')


	else:
		f = UserRegistration()

	return render(request,'blog/register.html',{'form':f})



# class PostCreateView(LoginRequiredMixin,CreateView): #user can only access pages using this if they are logged in
# 	model = Post

# 	fields = ['title','content','image']


# 	def form_valid(self,form):
# 		form.instance.author = self.request.user #set the author to the current logged in user
# 		return super().form_valid(form)

def indexView(request):
    form = PostForm()
    posts = Post.objects.all()
    return render(request, "blog/index.html", {"form": form, "posts": posts})


def PostCreateView(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        form = PostForm(request.POST)
        # save the data and after fetch the object in instance
        if form.is_valid():
            instance = form.save()
            # serialize in new friend object in json
            ser_instance = serializers.serialize('json', [ instance, ])
            # send to client side.
            return JsonResponse({"instance": ser_instance}, status=200)
        else:
            # some form errors occured.
            return JsonResponse({"error": form.errors}, status=400)

    # some error occured
    return JsonResponse({"error": ""}, status=400)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Reshoketswe Matloga">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  
    <title>Samantha</title>
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a class="text-dark" href="{%url 'home'%}">Samantha</a>
      </h5>
      {% if user.is_authenticated %}
        <nav class="my-2 my-md-0 mr-md-3">
          <a class="p-2 text-dark" href="{%url 'post_'%}">Post</a>
          <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
        </nav>
      {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">login</a>
        <a class="btn btn-outline-primary" href="{% url 'register' %}">Sign up</a>
      {% endif %}
    </div>

    <div class="container">
    	{% block content %}

  	  {% endblock%}
      <div></div>
   </div>





<!-- 
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
	{% for info in key_1%}
		<div style="width:900px; margin:0 auto;">
			<div class="col-md-15">
			  <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
			    <div class="col p-4 d-flex flex-column position-static">
			      <h2 class="blog-post-title"> {{ info.title }} </h2>
			      <p class="blog-post-meta">{{ info.date }}  <a href="#">{{ info.author }}</a></p>
			      <hr> <!-- inserts horizontal rule -->
			      <p> {{ info.content }} </p>
			    </div>
			    	<div class="col-auto d-none d-lg-block">
	          			<rect width="100%" height="100%" fill="#55595c"/>
	        		</div>
			  </div>
			</div>
		</div>
	{% endfor %}

{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
<!-- {% load crispy_forms_tags %} -->
{% block content %}

	<div class="container-fluid">
	    <form id="post-form">
	        <div class="col">
	            {% csrf_token %}
	            {% for field in form %}
	            <div class="form-group col-4">
	                <label class="col-12">{{ field.label }}</label>
	                {{ field }}
	                
	            </div>
	            {% endfor %}
	            
					<button class= "info">Post</button>
				
	        </div>
	    <form>
	</div>
	<hr />

	{% for info in posts%}
		<div style="width:900px; margin:0 auto;">
			<div class="col-md-15" id="my_post">
			  <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
			    <div class="col p-4 d-flex flex-column position-static">
			      <h2 class="blog-post-title"> {{ info.title }} </h2>
			      <p class="blog-post-meta">{{ info.date | date:"Y-m-d"}}  <a href="#">{{ info.author }}</a></p>
			      <hr> <!-- inserts horizontal rule -->
			      <p> {{ info.content }} </p>
			    </div>
			    	<div class="col-auto d-none d-lg-block">
	          			<rect width="100%" height="100%" fill="#55595c"/>
	        		</div>
			  </div>
			</div>
		</div>
	{% endfor %}

{% endblock content %}

{% block javascript %}
	<script>
	    /*
	        On submiting the form, send the POST ajax
	        request to server and after successfull submission
	        display the object.
	    */
	    $("#post-form").submit(function (e) {
	        // preventing from page reload and default actions
	        e.preventDefault();
	        // serialize the data for sending the form data.
	        var serializedData = $(this).serialize();
	        // make POST ajax call
	        $.ajax({
	            type: 'POST',
	            url: "{% url 'post_' %}",
	            data: serializedData,
	            success: function (response) {
	                // on successfull creating object
	                // 1. clear the form.
	                $("#post-form").trigger('reset');
	                // 2. focus to nickname input 
	                $("#id_author").focus();

	                // display the newly friend to table.
	                var instance = JSON.parse(response["instance"]);
	                var fields = instance[0]["fields"];
	                $("#my_post").prepend(
	                    `<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
			    <div class="col p-4 d-flex flex-column position-static">
			      
			      <p class="blog-post-meta"> <a href="#">${fields["author"]||""}</a></p>
			      <hr> <!-- inserts horizontal rule -->
			      <p> ${fields["content"]||""} </p>
			    </div>
			    	<div class="col-auto d-none d-lg-block">
	          			<rect width="100%" height="100%" fill="#55595c"/>
	        		</div>
			  </div>`
	                )
	            },
	            error: function (response) {
	                // alert the error if any error occured
	                alert(response["responseJSON"]["error"]);
	            }
	        })
	    })
	</script>
{% endblock javascript %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{%load crispy_forms_tags%}

{%block content%}

	<div class = "content-section">
		<form method = "POST">
			{% csrf_token %}
			<fieldset class = "form-group">
				<legend class = "border-bottom mb-4">Login</legend>

				{{form | crispy}}
			</fieldset>
			<div class="form-group">
				<button class= "info">login</button>
			</div>

			

		</form>
		
	</div>
	
{% endblock %}

blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
{%load crispy_forms_tags%}

{%block content%}

	<div class = "content-section">

				<legend class = "border-bottom mb-4">Logout</legend>
				<div>
					wana go back in? <a href="{% url 'login' %}">login</a>
				</div>
	
	</div>
	
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<form method = "post">

	{%  csrf_token %}

	{{form | crispy }}

	<button type = "submit" class = "btn-btn-info">post</button>

</form>

{%  endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method = "post">

	{%  csrf_token %}

	{{form | crispy }}

	<button type = "submit" class = "btn-btn-info">Sign Up</button>

</form>

{%  endblock %}